### ISSUE TITLE
Update the webserver to run healthchecks on the app database & Redis cache on startup

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fidesops#512]
### Is your feature request related to a specific problem?

The first time you try to setup Fidesops, you're likely going to run into some issues with connecting to the two dependencies: your application database (Postgres) and the cache (Redis).

Right now if you misconfigure your database credentials and run the server, you get a large error message:
```
fidesops_1  | INFO:fidesops.main:****************fidesops****************
fidesops_1  | INFO:fidesops.main:Running any pending DB migrations...
fidesops_1  | Traceback (most recent call last):
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
fidesops_1  |     return fn()
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 301, in connect
fidesops_1  |     return _ConnectionFairy._checkout(self)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 761, in _checkout
fidesops_1  |     fairy = _ConnectionRecord.checkout(pool)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
fidesops_1  |     rec = pool._do_get()
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
fidesops_1  |     return self._create_connection()
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
fidesops_1  |     return _ConnectionRecord(self)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
fidesops_1  |     self.__connect()
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
fidesops_1  |     pool.logger.debug("Error on connect(): %s", e)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
fidesops_1  |     compat.raise_(
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
fidesops_1  |     raise exception
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
fidesops_1  |     connection = pool._invoke_creator(self)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
fidesops_1  |     return dialect.connect(*cargs, **cparams)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
fidesops_1  |     return self.dbapi.connect(*cargs, **cparams)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
fidesops_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
fidesops_1  | psycopg2.OperationalError: could not connect to server: Connection refused
fidesops_1  |   Is the server running on host "db" (172.29.0.3) and accepting
fidesops_1  |   TCP/IP connections on port 9432?
fidesops_1  | 
fidesops_1  | 
fidesops_1  | The above exception was the direct cause of the following exception:
fidesops_1  | 
fidesops_1  | Traceback (most recent call last):
fidesops_1  |   File "/usr/local/bin/fidesops", line 33, in <module>
fidesops_1  |     sys.exit(load_entry_point('fidesops', 'console_scripts', 'fidesops')())
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
fidesops_1  |     return self.main(*args, **kwargs)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
fidesops_1  |     rv = self.invoke(ctx)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
fidesops_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
fidesops_1  |     return ctx.invoke(self.callback, **ctx.params)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
fidesops_1  |     return callback(*args, **kwargs)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
fidesops_1  |     return f(get_current_context(), *args, **kwargs)
fidesops_1  |   File "/fidesops/src/fidesops/cli.py", line 20, in webserver
fidesops_1  |     start_webserver()
fidesops_1  |   File "/fidesops/src/fidesops/main.py", line 37, in start_webserver
fidesops_1  |     init_db(config.database.SQLALCHEMY_DATABASE_URI)
fidesops_1  |   File "/fidesops/src/fidesops/db/database.py", line 40, in init_db
fidesops_1  |     upgrade_db(alembic_config)
fidesops_1  |   File "/fidesops/src/fidesops/db/database.py", line 32, in upgrade_db
fidesops_1  |     command.upgrade(alembic_config, revision)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 294, in upgrade
fidesops_1  |     script.run_env()
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 490, in run_env
fidesops_1  |     util.load_python_file(self.dir, "env.py")
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
fidesops_1  |     module = load_module_py(module_id, path)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/util/compat.py", line 184, in load_module_py
fidesops_1  |     spec.loader.exec_module(module)
fidesops_1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
fidesops_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
fidesops_1  |   File "/fidesops/src/migrations/env.py", line 99, in <module>
fidesops_1  |     run_migrations_online()
fidesops_1  |   File "/fidesops/src/migrations/env.py", line 84, in run_migrations_online
fidesops_1  |     with connectable.connect() as connection:
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
fidesops_1  |     return self._connection_cls(self, close_with_result=close_with_result)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
fidesops_1  |     else engine.raw_connection()
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
fidesops_1  |     return self._wrap_pool_connect(self.pool.connect, _connection)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3215, in _wrap_pool_connect
fidesops_1  |     Connection._handle_dbapi_exception_noconnection(
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2068, in _handle_dbapi_exception_noconnection
fidesops_1  |     util.raise_(
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
fidesops_1  |     raise exception
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
fidesops_1  |     return fn()
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 301, in connect
fidesops_1  |     return _ConnectionFairy._checkout(self)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 761, in _checkout
fidesops_1  |     fairy = _ConnectionRecord.checkout(pool)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
fidesops_1  |     rec = pool._do_get()
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
fidesops_1  |     return self._create_connection()
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
fidesops_1  |     return _ConnectionRecord(self)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
fidesops_1  |     self.__connect()
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
fidesops_1  |     pool.logger.debug("Error on connect(): %s", e)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
fidesops_1  |     compat.raise_(
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
fidesops_1  |     raise exception
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
fidesops_1  |     connection = pool._invoke_creator(self)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
fidesops_1  |     return dialect.connect(*cargs, **cparams)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
fidesops_1  |     return self.dbapi.connect(*cargs, **cparams)
fidesops_1  |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
fidesops_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
fidesops_1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
fidesops_1  |   Is the server running on host "db" (172.29.0.3) and accepting
fidesops_1  |   TCP/IP connections on port 9432?
fidesops_1  | 
fidesops_1  | (Background on this error at: http://sqlalche.me/e/14/e3q8)
```

The error message ends up being helpful ("Connection refused, Is the server running on host "db" (172.29.0.3) and accepting TCP/IP connections on port 9432?"), but the large stack trace isn't that helpful for a regular user. So, as a user, you end up tinkering with the config variables until the error messages go away.

However... if you misconfigure your Redis credentials, everything starts up normally... but you'll eventually get an error the first time you use a feature that relies on Redis (e.g. creating a privacy request). That may be days later!

So overall, we just need a better solution on startup that runs some "healthchecks" on both the app database & Redis cache so that a new user can more easily troubleshoot common problems.

See https://github.com/ethyca/fides/issues/562 which is also tackling this same problem on fidesctl

### Describe the solution you'd like

Here's my recommendation:
1. fidesops should attempt to connect to both the app db & Redis cache on startup
2. fidesops should catch any exceptions and log an ERROR message with the actual error (e.g. "sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server...") but suppress the (largely unhelpful) stacktrace
3. if either the database or cache healthcheck fails, the server should not start... for now (I'd like to change this behaviour in the coming months when the "config UI" is accessible, so that we can show these startup errors in the UI)
4. these database & cache healthchecks should *also* be returned in the `/health` API, so something like:
```
{
  "status": "healthy",
  "version": "1.4.1",
  "database": "healthy",
  "cache": "healthy"
}
```

### Describe alternatives you've considered, if any

I haven't put a ton of thought into other options here, so definitely open to discussing ideas

**Comment by eastandwestwind** [comment]
@seanpreston / @NevilleS due to new behavior from our newly added Celery config, I'm looking for help brainstorming options here.


*The problem* 

After checking out latest `main`, I altered the `postgres` config to an invalid pw, and ran `make server`. Instead of replicating the original large err message above, I get the following:

```
ERROR: for celery  Container "a0af22c43d44" is unhealthy.
ERROR: Encountered errors while bringing up the project.
make: *** [server] Error 1
```

This is because we've recently added Celery to our `docker-compose.yml` and added both `postgres` and `redis` to its `depends_on` config (upon removing these lines, I was able to replicate original err message): 

```
depends_on:
      fidesops:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
```

So instead of failing at `sqlalchemy` level, we fail at docker start-up with an even more unhelpful err message than before.


*My thoughts*

* I assume we need to keep the `depends_on` config in place for `Celery`. **Can we remove `depends_on` at docker level and instead write app-level code for this?**
* I didn't see a way to surface an err message from `depends_on` failures (https://docs.docker.com/compose/compose-file/#depends_on)
* I wanted to see if we could surface a better err by adding explicit `healthcheck` commands to `postgres` and `redis`:

```
db:
    . . .
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5
      . . .

  redis:
    . . .
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 15s
      timeout: 5s
      retries: 5
    . . .

  celery:
    . . .
    depends_on:
      fidesops:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
```

This config still resulted in an unhealthy `Celery` container err message:
```
ERROR: for celery  Container "cbf2b2615cec" is unhealthy.
ERROR: Encountered errors while bringing up the project.
make: *** [server] Error 1
```

* Similarly, I don't see a way to surface err message from `healthcheck` - https://docs.docker.com/compose/compose-file/#healthcheck

Any other options here I'm missing?

**Comment by eastandwestwind** [comment]
We've determined that both `db` and `fidesops` dependencies can be removed from `celery` config.

With this, I'm able to catch connection errors from our db, and throw a clearer message / stack trace:

```
fidesops    | INFO:fidesops.main:****************fidesops****************
fidesops    | INFO:fidesops.main:Running any pending DB migrations...
db_1        | 2022-06-21 14:21:28.011 UTC [32] FATAL:  password authentication failed for user "postgres"
db_1        | 2022-06-21 14:21:28.011 UTC [32] DETAIL:  Password does not match for user "postgres".
db_1        | 	Connection matched pg_hba.conf line 99: "host all all all md5"
fidesops    | ERROR:fidesops.main:Connection to database failed: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
fidesops    |
fidesops    | (Background on this error at: http://sqlalche.me/e/14/e3q8)
fidesops    | INFO:fidesops.main:Running Redis connection test...
fidesops    | INFO:apscheduler.scheduler:Scheduler started
fidesops    | INFO:fidesops.main:Starting scheduled request intake...
db_1        | 2022-06-21 14:21:28.080 UTC [33] FATAL:  password authentication failed for user "postgres"
db_1        | 2022-06-21 14:21:28.080 UTC [33] DETAIL:  Password does not match for user "postgres".
db_1        | 	Connection matched pg_hba.conf line 99: "host all all all md5"
fidesops    | Traceback (most recent call last):
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
fidesops    |     return fn()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 301, in connect
fidesops    |     return _ConnectionFairy._checkout(self)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 761, in _checkout
fidesops    |     fairy = _ConnectionRecord.checkout(pool)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
fidesops    |     rec = pool._do_get()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
fidesops    |     self._dec_overflow()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
fidesops    |     compat.raise_(
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
fidesops    |     raise exception
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
fidesops    |     return self._create_connection()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
fidesops    |     return _ConnectionRecord(self)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
fidesops    |     self.__connect()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
fidesops    |     pool.logger.debug("Error on connect(): %s", e)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
fidesops    |     compat.raise_(
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
fidesops    |     raise exception
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
fidesops    |     connection = pool._invoke_creator(self)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
fidesops    |     return dialect.connect(*cargs, **cparams)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
fidesops    |     return self.dbapi.connect(*cargs, **cparams)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
fidesops    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
fidesops    | psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"
fidesops    |
fidesops    |
fidesops    | The above exception was the direct cause of the following exception:
fidesops    |
fidesops    | Traceback (most recent call last):
fidesops    |   File "/usr/local/bin/fidesops", line 33, in <module>
fidesops    |     sys.exit(load_entry_point('fidesops', 'console_scripts', 'fidesops')())
fidesops    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
fidesops    |     return self.main(*args, **kwargs)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
fidesops    |     rv = self.invoke(ctx)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
fidesops    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
fidesops    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
fidesops    |     return ctx.invoke(self.callback, **ctx.params)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
fidesops    |     return __callback(*args, **kwargs)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
fidesops    |     return f(get_current_context(), *args, **kwargs)
fidesops    |   File "/fidesops/src/fidesops/cli.py", line 20, in webserver
fidesops    |     start_webserver()
fidesops    |   File "/fidesops/src/fidesops/main.py", line 92, in start_webserver
fidesops    |     initiate_scheduled_request_intake()
fidesops    |   File "/fidesops/src/fidesops/tasks/scheduled/tasks.py", line 22, in initiate_scheduled_request_intake
fidesops    |     onetrust_config: Optional[StorageConfig] = StorageConfig.get_by(
fidesops    |   File "/fidesops/src/fidesops/db/base_class.py", line 128, in get_by
fidesops    |     return db.query(cls).filter_by(**kwargs).first()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2750, in first
fidesops    |     return self.limit(1)._iter().first()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2834, in _iter
fidesops    |     result = self.session.execute(
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1676, in execute
fidesops    |     conn = self._connection_for_bind(bind, close_with_result=True)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1526, in _connection_for_bind
fidesops    |     return self._transaction._connection_for_bind(
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
fidesops    |     conn = bind.connect()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
fidesops    |     return self._connection_cls(self, close_with_result=close_with_result)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
fidesops    |     else engine.raw_connection()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
fidesops    |     return self._wrap_pool_connect(self.pool.connect, _connection)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3215, in _wrap_pool_connect
fidesops    |     Connection._handle_dbapi_exception_noconnection(
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2068, in _handle_dbapi_exception_noconnection
fidesops    |     util.raise_(
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
fidesops    |     raise exception
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
fidesops    |     return fn()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 301, in connect
fidesops    |     return _ConnectionFairy._checkout(self)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 761, in _checkout
fidesops    |     fairy = _ConnectionRecord.checkout(pool)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
fidesops    |     rec = pool._do_get()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
fidesops    |     self._dec_overflow()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
fidesops    |     compat.raise_(
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
fidesops    |     raise exception
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
fidesops    |     return self._create_connection()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
fidesops    |     return _ConnectionRecord(self)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
fidesops    |     self.__connect()
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
fidesops    |     pool.logger.debug("Error on connect(): %s", e)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
fidesops    |     compat.raise_(
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
fidesops    |     raise exception
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
fidesops    |     connection = pool._invoke_creator(self)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
fidesops    |     return dialect.connect(*cargs, **cparams)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
fidesops    |     return self.dbapi.connect(*cargs, **cparams)
fidesops    |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
fidesops    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
fidesops    | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
fidesops    |
fidesops    | (Background on this error at: http://sqlalche.me/e/14/e3q8)
```
